version: '3.8'

services:
  lancamentos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - db
      - rabbitmq
    networks:
      app-network:
        ipv4_address: 172.18.0.3
 

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sistemacomercial
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 172.18.0.2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      app-network:
        ipv4_address: 172.18.0.4

  saldo-consolidado:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - rabbitmq
    networks:
      app-network:
        ipv4_address: 172.18.0.5

volumes:
  postgres_data:
  
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24